# Generated by Django 3.2.4 on 2021-07-14 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210714_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 14, 51, 28, 697187, tzinfo=utc)),
        ),
    ]
